name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout репозиторий
        uses: actions/checkout@v3

      - name: 🔐 Подключение к серверу и деплой
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /smart
            git pull origin main
            npm ci
            npm run build
            pm2 restart app || pm2 start npm --name "app" -- run start
