name: 🚀 Deploy Full Project to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout репозитория
        uses: actions/checkout@v3

      - name: 🟢 Установить Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 🛠 Сборка проекта
        run: |
          npm ci
          npm run build

      - name: 📤 Скопировать проект на сервер (scp -r)
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "."                # копируем всё, как scp -r .
          target: "/smart" # куда копировать на сервере

      - name: 🚀 Запустить билд и старт на сервере
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /smart
            npm ci
            npm run build
            pm2 restart app || pm2 start npm --name "app" -- run start